# Generated by Django 5.0.2 on 2024-02-25 09:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0002_remove_category_picture_remove_category_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('mrp', models.CharField(default=0, max_length=50)),
                ('discount', models.CharField(default=0, max_length=50)),
                ('price', models.CharField(default=0, max_length=50)),
                ('thumbnail', models.ImageField(null=True, upload_to='images/')),
                ('added', models.DateField(default=datetime.datetime.now, null=True)),
                ('updated', models.DateField(default=datetime.datetime.now, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Category.category')),
            ],
        ),
    ]
