# Generated by Django 5.0.2 on 2024-02-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('added', models.DateField(null=True)),
                ('updated', models.DateField(null=True)),
            ],
        ),
    ]
