# Generated by Django 5.0.2 on 2024-02-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_remove_category_category_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
