# Generated by Django 5.0.2 on 2024-03-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_rename_category_inventory_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='no_of_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
