# Generated by Django 5.0.2 on 2024-02-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.PositiveBigIntegerField(default=0)),
                ('email', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
            ],
        ),
    ]
