# Generated by Django 5.0.2 on 2024-02-25 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addexpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=50)),
                ('describtion', models.CharField(max_length=50)),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime.now, null=True)),
            ],
        ),
    ]
