# Generated by Django 5.0.2 on 2024-02-23 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(default=0)),
                ('product_id', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('grandTotal', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime.now, null=True)),
            ],
        ),
    ]
